### ISSUE TITLE
Serilog.dll binding redirects added to all projects

### ISSUE THREAD

**Issue by gdoten** [destructurama/attributed#1]
When I install Destructurama.Attributed in our solution it adds a binding redirect to Serilog.dll, mapping 0.0.0.0-1.5.0.0 to 1.5.0.0 (I think those are the version numbers).

The problem is that we have 148 projects in our solution (I know; don't ask) and if a project does not have an app.config or web.config file, installing Attributed adds one to the project for us. It also adds the binding redirect to any existing app.config/web.config files.

We know we have an appropriate minimum version of Serilog, so why is Attributed doing this? (Hopefully this isn't really a NuGet question.)

**Comment by nblumhardt** [comment]
Hi Glenn; yes, unfortunately this is NuGet's behavior. I'll try updating the version of Serilog used by the package to see if this helps. Cheers!

**Comment by gdoten** [comment]
Perfect, that did it Nicholas! We no longer get app.config files being generated. Thank you for your always-speeding reply and resolution!
