### ISSUE TITLE
Memory leak when using .Destructure.UsingAttributes(x => x.IgnoreNullProperties = true)

### ISSUE THREAD

**Issue by PawelTroka** [destructurama/attributed#116]
**Describe the bug**
Memory leak when using .Destructure.UsingAttributes(x => x.IgnoreNullProperties = true)

**Expected behavior**
Memory usage should be around the same as without this attribute.

**Comment by sungam3r** [comment]
@PawelTroka If this issue is still actual for you then please provide additional information. Small example demonstrating memory leak will be the best option.

**Comment by sungam3r** [comment]
@PawelTroka I'm closing this one, because I do not see I can do anything here without providing additional information. Feel free to reopen if you have.
