### ISSUE TITLE
Can Destructure.UsingAttributes() be configured in .NET Framework (4.8) from app.config?

### ISSUE THREAD

**Issue by kazepis** [destructurama/attributed#118]
I cannot find any documentation whether this is supported or not and how.
I can use it in code `.Destructure.UsingAttributes();` but can I configure it inside app.config somehow?
Thanx!

**Comment by kazepis** [comment]
Anybody?

**Comment by sungam3r** [comment]
@kazepis  you may find some info here https://github.com/serilog/serilog/wiki/AppSettings

https://stackoverflow.com/questions/67271471/how-do-you-configure-destructurama-attributes-destructure-usingattribues-in-j

https://github.com/serilog/serilog-settings-appsettings/issues/20

**Comment by sungam3r** [comment]
Closing. @kazepis I hope you found answers.
