### ISSUE TITLE
Unexpected GetPropertiesRecursive

### ISSUE THREAD

**Issue by Rogmodr** [destructurama/attributed#12]
Hi! Me again :)
I wondering why GetPropertiesRecursive not looking into properties/fields types.

Example:
AuthMsg
{
    UserAuthData AuthData { get; set; }
}

UserAuthData
{
    string UserName { get; set; }
    [NotLogged]
    string Password { get; set; }
}

If i log AuthMsg object Password property will be logged.

**Comment by nblumhardt** [comment]
Hi! Just created #13 to try this out - works as far as I can tell. Can you come up with a test case that fails? Cheers!

**Comment by nblumhardt** [comment]
Closing without further info, but please jump in if you have a repro. Thanks!
