### ISSUE TITLE
Ability to add [NotLogged] but configure for the Microsoft ILogger/SerilogILogger logging levels

### ISSUE THREAD

**Issue by bensmith009988** [destructurama/attributed#120]
It would be really nice to have a configurable option on all of the types of ignorable attributes for ignoring properties within a log, but be able to specify that they are ignore from "this logging level and up." We have certain fields on our models we only want to log, when the ILogger logging level is logging this object at say Information and below, for example. This is because we have different logging specifications for different environments, and we only want to log (say passwords and authentication tokens for example) when the app is configured to run in debug mode.

**Comment by mobilebilly** [comment]
FYI, The log level is not currently accessible by the IDestructingPolicy which is discussed here https://github.com/serilog/serilog/issues/2105

So the enhancement is not possible at the moment

**Comment by sungam3r** [comment]
@mobilebilly Thanks for your answer. @bensmith009988 I think we can return back here if/when serilog core project adds support for such feature.
