### ISSUE TITLE
Support log property individually

### ISSUE THREAD

**Issue by rickykiet83** [destructurama/attributed#124]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

I have class like this:
```
public class Payment
{
    public int PaymentId { get; set; }

    public Guid UserId { get; set; }

    public DateTime OccuredAt { get; set; }

    [LogMasked]
    public string Email { get; set; }
}

var payment = new Payment
{
    PaymentId = 1,
    UserId = Guid.NewGuid(),
    Email = "abc@gmail.com",
    OccuredAt = DateTime.UtcNow
};

logger.Information("Received payment with details {@Payment}", payment);
logger.Information("Received payment with details Payment Id: {PaymentId}, Email: {Email}", payment.PaymentId, payment.Email);
```
When using Destructurama.Attributed, the [LogMasked] attribute works only when logging the entire object as a structured property, like {@Payment}. Unfortunately, if we log properties individually ({Email}), Serilog doesn’t apply the attribute-based masking by default.

**Describe the solution you'd like**
This is optional description of what you want to happen.
Create a custom attribute to indicate that field is masked as well, ensuring that sensitive fields are consistently masked regardless of how they’re logged.

**Comment by sungam3r** [comment]
> Unfortunately, if we log properties individually ({Email}), Serilog doesn’t apply the attribute-based masking by default.

This is incorrect to say that Serilog doesn't apply attribute-based masking. Especially _by default_. Value that you pass to serilog api is just a string **variable**. Called API knows nothing about its source. What you describing just doesn't work the way you think.
