### ISSUE TITLE
Ignoring methods with custom properties 

### ISSUE THREAD

**Issue by jamez14** [destructurama/attributed#2]
Is it possible to ignore a method (or even file) altogether? The issue I am encountering is when Serilog logs a method that does not use a predefined object in which I can add the `[NotLogged]` attribute to. For example, a method call that looks like this:

``` c#
public SomeResponse GetMember(GetMemberObject request)
{
    var member = memberRepository.GetMemberByCredentials(request.Email, request.Password);
    ... 
}
```

and the method signature for `GetMemberByCredentials` is: `GetMemberByCredentials(string email, string password);`. I want to be able to ignore the `string password` property from being logged. Is this possible? Or is the only "work around" to always pass in the object that contains the `NotLogged` attribute?

**Comment by nblumhardt** [comment]
Hi James - I don't see any Serilog code above; are you using something like Fody to weave logging in?

**Comment by nblumhardt** [comment]
Closing until we have further info. Thanks!
