### ISSUE TITLE
No signature on version 2.0 (and beyond)?

### ISSUE THREAD

**Issue by Scott-Foutz** [destructurama/attributed#30]
We're attempting to use v 2.0.0 and do not see a signature. We're having trouble creating a bindingRedirect between a prior signed version and the unsigned 2.0. Specifying the publickeytoken in the redirect appears to be the cause of the trouble. Just wanted to ask if we were missing something or if there is a workaround. Thanks

**Comment by SimonCropp** [comment]
@nblumhardt any objection to me re strongnaming this?

**Comment by nblumhardt** [comment]
Sounds like a plan; thanks for the help, @SimonCropp! 👍

**Comment by SimonCropp** [comment]
this has now been deployed
