### ISSUE TITLE
LogMasked PreserveLength ignored when both ShowLast and ShowFirst specified

### ISSUE THREAD

**Issue by alexandr-osprey** [destructurama/attributed#34]
Initial data

> 1234567891234567891

```
[LogMasked(PreserveLength = true,  ShowLast = 4)]
```

> ***************7891

```
[LogMasked(PreserveLength = true,  ShowLast = 4, ShowFirst = 6)]
```

> 123456***7891

Expected result

> 123456*********7891

Judjing by the source code the attribute is simply ignored in this case.
Destructurama.Attributed, Version=2.0.0.0

**Comment by SimonCropp** [comment]
this has now been deployed
