### ISSUE TITLE
LogReplaced default value

### ISSUE THREAD

**Issue by daniel-white** [destructurama/attributed#42]
`Regex.Replace(string, string, string, RegexOptions)` returns the source string if it isn't a match. Is there a way that the `LogReplaced` have a fallback in the event it doesn't match.

Also, might be good to specify a timeout on the call to `.Replace`.

**Comment by SimonCropp** [comment]
Looks good. can u submit a PR?

**Comment by sungam3r** [comment]
See #42. I added timeout but not fallback. The timeout behavior is obvious but fallback may be some custom `Func` so I think that it will be better to write your own class implementing `IPropertyDestructuringAttribute`.
