### ISSUE TITLE
DestructureObjects = true Not Working

### ISSUE THREAD

**Issue by bsulliva** [destructurama/attributed#47]
Hello, I'm using this github package, serilog-timings, and destructurama.attributed. I've found that when I set destructureObjects to true in the following code, op.Complete("Result", response, true);, it does not enforce the Destructure.MaxDepth and Destrcuture.UsingAttributes. It is only being enforced in the message template when I use the @ operator. I've also seen when using .ForContext(), its the same thing, log.ForContext("RequestBody", request, true).

Is it possible to apply destructuring rules to both?

**Comment by SimonCropp** [comment]
can you share a failing unit test as a pull request

**Comment by sungam3r** [comment]
> It is only being enforced in the message template when I use the @ operator.

I think that this is the right behavior. Otherwise `ToString()` is used without traversing object structure. See https://github.com/serilog/serilog/wiki/Structured-Data#objects : 

> When Serilog doesn't recognise the type, and no operator is specified (see below) then the object will be rendered using ToString().

And https://github.com/serilog/serilog/wiki/Structured-Data#preserving-object-structure .

**Comment by chase-miller** [comment]
> I think that this is the right behavior.

When I call `ForContext()` and supply `true` for the `destructureObjects` argument, the `LoggerDestructuringConfiguration.ByTransforming<T>()` setup is leveraged. Why wouldn't `LoggerDestructuringConfiguration.UsingAttributes()` work too?
