### ISSUE TITLE
Can't add attributes to properties of C#9 record classes (Attribute NotLogged is not valid on this dec type)

### ISSUE THREAD

**Issue by goblinfactory** [destructurama/attributed#50]
Given I am using C# records
I want to decorate PI properties with [NotLogged] attribute
So that the properties are not logged

Example

```csharp
   public record LoginRequest([Required][EmailAddress] string EmailAddress, [NotLogged][Required] string Password);
```

gives me a compile error, `Attribute NotLogged is not valid on this declaration type.

**Comment by goblinfactory** [comment]
Ah! Fixed... solution is to prefix the attribute with property. I never knew you could do this in C#... live and learn!
maybe leave this issue open for a bit, so that I can create a PR some time to update documentation to show this? It's really useful to know.

fix like so ...
```csharp
public record LoginRequest([Required][EmailAddress] string EmailAddress, [property:NotLogged][Required] string Password);
```

**Comment by goblinfactory** [comment]
oops, now it's just ignored. So you CAN add a [NotLogged] property to a C# record property, but it seems to be ignored?

yelp! ...

**Comment by SimonCropp** [comment]
there are many qwerks with records and properties. unfortunately it is not responsibility of this project to document those
