### ISSUE TITLE
Provide ability to default records to masked, with override on specific properties

### ISSUE THREAD

**Issue by dan-drews** [destructurama/attributed#63]
Good morning!

We are working on a project where we deal with a decent amount of sensitive data, and while logs are very useful, there are concerns about us adding new types, and forgetting to Mask a field (or many fields) on it.

It'd be nice if when we initialize Destructurama we could make a property such as `MaskUnlessAllowed`.

This would implicitly apply `LogMasked` to every field, unless that field specifically had `AllowLog` or something along those lines.

If we have the bandwidth to do so, we may take a stab at this on our end and submit a PR for it. Would this feature be accepted if added? If so, any feedback on approach or naming?

Thanks!

**Comment by dan-drews** [comment]
In program.cs

`.Destructure.UsingAttributes(DestructureMethod.MaskUnlessAllowed)`

**Comment by sungam3r** [comment]
While theoretically it is possible the main question is how existing attributes should work in that case? Note that `UsingAttributes` is not about masking values. It is about destructuring objects using specific rules programmed through attributes. Masking is just a one of such rules. This package provides some attributes and some of them do not relate to masking, for example, `LogWithNameAttribute`. Someone else may have custom attribute too.

**Comment by sungam3r** [comment]
Closed due to inactivity.
