### ISSUE TITLE
Add a render masked string only method in `IPropertyDestructuringAttribute`

### ISSUE THREAD

**Issue by juchom** [destructurama/attributed#71]
Would it be possible to add a method to the interface that only return the masked string ?

The main reason behind this is to leverage this attributes in other parts of an application.

For exemple we have this class

```csharp
public class ResetPassword
{
    [LogMasked]
    public string Password { get; set; }
    [LogMasked]
    public string ConfirmPassword { get; set; }
}
```

If I log this object with serilog everyhting is fine.

What would be great is to be able to have the rendered string directly in order to use them in custom exception's message for exemple.

**Comment by sungam3r** [comment]
> Would it be possible to add a method to the interface that only return the masked string ?

What interface?

**Comment by sungam3r** [comment]
If I understand correctly you need `LogMaskedAttribute.FormatMaskedValue` to be public.

**Comment by sungam3r** [comment]
`new LogMaskedAttribute { ShowFirst = 3 }.GetMaskedValue("abcdef")`

**Comment by juchom** [comment]
Hello,

To be honest, I don't remember what was my exact use case when I opened this issue.

But I was probably trying to have the properties rendered like it is in Serilog.

Probably an extension method like `ToLoggingString()` that applies the same transformation.

**Comment by sungam3r** [comment]
Do you still need such API?

**Comment by juchom** [comment]
I don't need it anymore right now.
