### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by cocowalla** [destructurama/attributed#8]
There is quite a bit of locking going on in `AttributedDestructuringPolicy` - I wonder if using a `ConcurrentDictionary` for the cache would be beneficial?

In any case, it would be nice to add a test that performs benchmarks, so the performance impact of using attributes can be assessed.

**Comment by nblumhardt** [comment]
In the latest `dev` version, there's still some locking, but the scope is reduced so that we do much less work under the lock.

Closing this for now, but always up for some perf improvements in the future :-)
