### ISSUE TITLE
Extension method `UsingAttributes(x => x.IgnoreNullProperties = true)` not callable in .NET 8 class library project

### ISSUE THREAD

**Issue by MelvLee** [destructurama/attributed#92]
I want to use the 'Ignore null properties' functionality in a .NET 8 class library project, however I cannot use the `UsingAttributes(x => x.IgnoreNullProperties = true)` extension method. I can only call the `UsingAttributes()` variant. The `NotLoggedIfNull` attribute is also not available for use.

**Comment by sungam3r** [comment]
![изображение](https://github.com/destructurama/attributed/assets/21261007/e147b00a-56ff-4191-bfdf-58dd110abdfd)

This code was not released yet. Will be published in v3.2 coming days. @nblumhardt OK?

**Comment by nblumhardt** [comment]
Seems like a freshen-up is overdue; thanks @sungam3r :+1:

**Comment by sungam3r** [comment]
https://github.com/destructurama/attributed/releases/tag/3.2.0
https://www.nuget.org/packages/Destructurama.Attributed/3.2.0

**Comment by MelvLee** [comment]
I have tried it and it works like a charm. Thank you
